In [1]:
import pandas as pd

In [13]:
pd.read_csv('csvs/pokemon.csv',encoding='ISO-8859-1')

        Pokemon      Type
0     Bulbasaur     Grass
1       Ivysaur     Grass
2      Venusaur     Grass
3    Charmander      Fire
4    Charmeleon      Fire
5     Charizard      Fire
6      Squirtle     Water
7     Wartortle     Water
8     Blastoise     Water
9      Caterpie       Bug
10      Metapod       Bug
11   Butterfree       Bug
12       Weedle       Bug
13       Kakuna       Bug
14     Beedrill       Bug
15       Pidgey    Normal
16    Pidgeotto    Normal
17      Pidgeot    Normal
18      Rattata    Normal
19     Raticate    Normal
20      Spearow    Normal
21       Fearow    Normal
22        Ekans    Poison
23        Arbok    Poison
24      Pikachu  Electric
25       Raichu  Electric
26    Sandshrew    Ground
27    Sandslash    Ground
28      Nidoran    Poison
29     Nidorina    Poison
..          ...       ...
691   Clauncher     Water
692   Clawitzer     Water
693  Helioptile  Electric
694   Heliolisk  Electric
695      Tyrunt      Rock
696   Tyrantrum      Rock
697      Amaura      Rock
698     Aurorus      Rock
699     Sylveon     Fairy
700    Hawlucha  Fighting
701     Dedenne  Electric
702     Carbink      Rock
703       Goomy    Dragon
704     Sliggoo    Dragon
705      Goodra    Dragon
706      Klefki     Steel
707    Phantump     Ghost
708   Trevenant     Ghost
709   Pumpkaboo     Ghost
710   Gourgeist     Ghost
711    Bergmite       Ice
712     Avalugg       Ice
713      Noibat    Flying
714     Noivern    Flying
715     Xerneas     Fairy
716     Yveltal      Dark
717     Zygarde    Dragon
718     Diancie      Rock
719       Hoopa   Psychic
720   Volcanion      Fire

[721 rows x 2 columns]

        Pokemon      Type
0     Bulbasaur     Grass
1       Ivysaur     Grass
2      Venusaur     Grass
3    Charmander      Fire
4    Charmeleon      Fire
5     Charizard      Fire
6      Squirtle     Water
7     Wartortle     Water
8     Blastoise     Water
9      Caterpie       Bug
10      Metapod       Bug
11   Butterfree       Bug
12       Weedle       Bug
13       Kakuna       Bug
14     Beedrill       Bug
15       Pidgey    Normal
16    Pidgeotto    Normal
17      Pidgeot    Normal
18      Rattata    Normal
19     Raticate    Normal
20      Spearow    Normal
21       Fearow    Normal
22        Ekans    Poison
23        Arbok    Poison
24      Pikachu  Electric
25       Raichu  Electric
26    Sandshrew    Ground
27    Sandslash    Ground
28      Nidoran    Poison
29     Nidorina    Poison
..          ...       ...
691   Clauncher     Water
692   Clawitzer     Water
693  Helioptile  Electric
694   Heliolisk  Electric
695      Tyrunt      Rock
696   Tyrantrum      Rock
697      Amaura      Rock
698     Aurorus      Rock
699     Sylveon     Fairy
700    Hawlucha  Fighting
701     Dedenne  Electric
702     Carbink      Rock
703       Goomy    Dragon
704     Sliggoo    Dragon
705      Goodra    Dragon
706      Klefki     Steel
707    Phantump     Ghost
708   Trevenant     Ghost
709   Pumpkaboo     Ghost
710   Gourgeist     Ghost
711    Bergmite       Ice
712     Avalugg       Ice
713      Noibat    Flying
714     Noivern    Flying
715     Xerneas     Fairy
716     Yveltal      Dark
717     Zygarde    Dragon
718     Diancie      Rock
719       Hoopa   Psychic
720   Volcanion      Fire

[721 rows x 2 columns]

In [15]:
data=pd.read_csv('csvs/pokemon.csv',encoding='ISO-8859-1',squeeze=True)
#converting into series

pandas.core.frame.DataFrame

# Accessing Particular COlumns

In [21]:
pokemon=pd.read_csv('csvs/pokemon.csv',encoding='ISO-8859-1',squeeze=True,usecols=['Pokemon'])

In [17]:
pokemon

        Pokemon
0     Bulbasaur
1       Ivysaur
2      Venusaur
3    Charmander
4    Charmeleon
5     Charizard
6      Squirtle
7     Wartortle
8     Blastoise
9      Caterpie
10      Metapod
11   Butterfree
12       Weedle
13       Kakuna
14     Beedrill
15       Pidgey
16    Pidgeotto
17      Pidgeot
18      Rattata
19     Raticate
20      Spearow
21       Fearow
22        Ekans
23        Arbok
24      Pikachu
25       Raichu
26    Sandshrew
27    Sandslash
28      Nidoran
29     Nidorina
..          ...
691   Clauncher
692   Clawitzer
693  Helioptile
694   Heliolisk
695      Tyrunt
696   Tyrantrum
697      Amaura
698     Aurorus
699     Sylveon
700    Hawlucha
701     Dedenne
702     Carbink
703       Goomy
704     Sliggoo
705      Goodra
706      Klefki
707    Phantump
708   Trevenant
709   Pumpkaboo
710   Gourgeist
711    Bergmite
712     Avalugg
713      Noibat
714     Noivern
715     Xerneas
716     Yveltal
717     Zygarde
718     Diancie
719       Hoopa
720   Volcanion

[721 rows x 1 columns]

In [22]:
pokemon.ndim

1

In [23]:
pokemon.is_unique

True

In [24]:
pokemon.shape

(721,)

In [25]:
pokemon.size

721

In [26]:
pokemon.name

'Pokemon'

In [33]:
pokemon.sort_values(ascending=False)

717       Zygarde
633      Zweilous
40          Zubat
569         Zorua
570       Zoroark
262     Zigzagoon
643        Zekrom
522     Zebstrika
144        Zapdos
334      Zangoose
716       Yveltal
468       Yanmega
192         Yanma
561        Yamask
715       Xerneas
177          Xatu
359        Wynaut
264       Wurmple
412      Wormadam
193        Wooper
526        Woobat
201     Wobbuffet
277       Wingull
39     Wigglytuff
292       Whismur
339      Whiscash
543    Whirlipede
546    Whimsicott
109       Weezing
69     Weepinbell
          ...
609          Axew
712       Avalugg
698       Aurorus
530        Audino
143      Articuno
303          Aron
682    Aromatisse
347       Armaldo
167       Ariados
566      Archeops
565        Archen
492        Arceus
58       Arcanine
23          Arbok
346       Anorith
180      Ampharos
590     Amoonguss
423       Ambipom
697        Amaura
333       Altaria
593     Alomomola
64       Alakazam
189         Aipom
305        Aggron
141    Aerodactyl
680     Aegislash
616      Accelgor
358         Absol
62           Abra
459     Abomasnow
Name: Pokemon, Length: 721, dtype: object

In [34]:
google = pd.read_csv("csvs/google.csv",squeeze=True)

In [56]:
google.sort_values(ascending=True).head()

11    49.95
9     50.07
0     50.12
10    50.70
12    50.74
Name: Stock Price, dtype: float64

In [63]:
google.sort_values

<bound method Series.sort_values of 3011    782.22
2859    776.60
3009    773.18
3007    772.88
3010    771.61
3008    771.07
2860    771.00
3006    768.79
2840    767.04
2843    766.81
2934    766.61
2882    764.65
2844    763.25
2858    762.51
2841    762.38
2845    762.37
2937    759.14
2933    759.00
2861    758.88
2851    758.09
2834    756.60
2835    755.98
2935    753.93
2932    753.20
2936    752.67
2842    752.54
2881    752.00
2931    751.72
2846    751.61
2921    750.53
         ...
28       65.47
29       64.74
27       63.37
24       60.35
25       59.86
21       59.62
23       59.13
26       59.07
22       58.86
20       58.69
19       56.93
18       55.94
17       55.69
2        54.65
1        54.10
5        53.90
16       53.70
6        53.02
4        52.95
15       52.61
3        52.38
8        51.13
13       51.10
14       51.10
7        50.95
12       50.74
10       50.70
0        50.12
9        50.07
11       49.95
Name: Stock Price, Length: 3012, dtype: float64>

# Index Sorting

In [73]:
pokemon1=pd.read_csv("csvs/pokemon.csv",squeeze=True,encoding='ISO-8859-1',usecols=['Pokemon'])

In [81]:
pokemon1.sort_values(ascending=True,inplace=True)

In [75]:
pokemon1.head()

459    Abomasnow
62          Abra
358        Absol
616     Accelgor
680    Aegislash
Name: Pokemon, dtype: object

In [78]:
pokemon1.sort_index()

0       Bulbasaur
1         Ivysaur
2        Venusaur
3      Charmander
4      Charmeleon
5       Charizard
6        Squirtle
7       Wartortle
8       Blastoise
9        Caterpie
10        Metapod
11     Butterfree
12         Weedle
13         Kakuna
14       Beedrill
15         Pidgey
16      Pidgeotto
17        Pidgeot
18        Rattata
19       Raticate
20        Spearow
21         Fearow
22          Ekans
23          Arbok
24        Pikachu
25         Raichu
26      Sandshrew
27      Sandslash
28        Nidoran
29       Nidorina
          ...
691     Clauncher
692     Clawitzer
693    Helioptile
694     Heliolisk
695        Tyrunt
696     Tyrantrum
697        Amaura
698       Aurorus
699       Sylveon
700      Hawlucha
701       Dedenne
702       Carbink
703         Goomy
704       Sliggoo
705        Goodra
706        Klefki
707      Phantump
708     Trevenant
709     Pumpkaboo
710     Gourgeist
711      Bergmite
712       Avalugg
713        Noibat
714       Noivern
715       Xerneas
716       Yveltal
717       Zygarde
718       Diancie
719         Hoopa
720     Volcanion
Name: Pokemon, Length: 721, dtype: object

# Extracting Values

In [82]:
pokemon1[10]

'Metapod'

In [83]:
pokemon1[[10,20,30,40]]

10      Metapod
20      Spearow
30    Nidoqueen
40        Zubat
Name: Pokemon, dtype: object

In [85]:
pokemon[50:101]

50        Dugtrio
51         Meowth
52        Persian
53        Psyduck
54        Golduck
55         Mankey
56       Primeape
57      Growlithe
58       Arcanine
59        Poliwag
60      Poliwhirl
61      Poliwrath
62           Abra
63        Kadabra
64       Alakazam
65         Machop
66        Machoke
67        Machamp
68     Bellsprout
69     Weepinbell
70     Victreebel
71      Tentacool
72     Tentacruel
73        Geodude
74       Graveler
75          Golem
76         Ponyta
77       Rapidash
78       Slowpoke
79        Slowbro
80      Magnemite
81       Magneton
82     Farfetch'd
83          Doduo
84         Dodrio
85           Seel
86        Dewgong
87         Grimer
88            Muk
89       Shellder
90       Cloyster
91         Gastly
92        Haunter
93         Gengar
94           Onix
95        Drowzee
96          Hypno
97         Krabby
98        Kingler
99        Voltorb
100     Electrode
Name: Pokemon, dtype: object